##########################################################################
#
#    PBFT Configuration
#
##########################################################################
PBFT:
    R: 4
    F: 1