---
################################################################################
#
#   PBFT PROPERTIES
#
#   - List all algorithm-specific properties here.
#   - Nest keys where appropriate, and sort alphabetically for easier parsing.
#
################################################################################
general:
    # Maximum number of validators/replicas we expect in the network
    # Keep the "N" in quotes, or it will be interpreted as "false".
    "N": 4

    # Number of byzantine nodes we will tolerate
    f: 1

    # Checkpoint period is the maximum number of pbft requests that must be
    # re-processed in a view change. A smaller checkpoint period will decrease
    # the amount of time required to recover from an error, but will decrease
    # overall throughput in normal case operation.
    K: 10

    # Affects the receive log size which is K * logmultiplier
    # The primary will only send sequence numbers which fall within K * logmultiplier/2 of
    # its high watermark, so this cannot be set to less than 2
    # For high volume/high latency environments, a higher log size may increase throughput
    logmultiplier: 4

    # Whether the replica should act as a byzantine one; useful for debugging on testnets
    byzantine: false